configuration: Release

version: 1.0.{build}

image: Visual Studio 2022

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

before_build:
  - dotnet restore
  
branches:
    only:
      - master

deploy:
  provider: NuGet
  api_key:
    secure: z6b5tfTOm7v82Ir+AbxYCFx+wF9koQI0ZRxS6Km7iCDkYpDD2UQEupYRpJVXdTBm
  skip_symbols: false
  artifact: /.*\.nupkg/
  
    

  
  


